name: CI

on:
  push:
    paths:
      - 'slides/**'
permissions:
  contents: write

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install
        run: pnpm install

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41
        with:
          path: ./slides
          dir_names: true
          dir_names_max_depth: '1'
      
      - name: Install Dependency
        if: steps.changed-files.outputs.all_changed_and_modified_files_count != '0'
        run: pnpm exec playwright install-deps

      - name: List all changed files
        if: steps.changed-files.outputs.all_changed_and_modified_files_count != '0'
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for file in "$ALL_CHANGED_FILES"; do
            echo "$file was changed"
            pnpm exec slidev build -o $PWD/dist/$file --base /$file/ slides/$file/slide.md
          done
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          folder: dist