name: Build Slide

on:
  push:
    paths:
      - 'slides/**'
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install
        run: pnpm install

      - name: Create Directory
        run: |
          mkdir dist
          cd slides
          find . -type d -exec mkdir -p ${{ github.workspace }}/dist/{} \;
          cd ${{ github.workspace }}

      - name: Identify changed slides folder
        id: changes
        run: |
          files=$(git diff --name-only --diff-filter=ACMRTUXB ${{ github.event.before }} ${{ github.sha }} | grep '^slides/' | sed 's|^slides/\([^/]*\)/.*$|\1|' | uniq)
          echo "slides_files<<EOF" >> $GITHUB_OUTPUT
          echo $files >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Build target file in slides folder
        if: ${{ steps.changes.outputs.slides_files }}
        run: |
          slides_folders="${{ steps.changes.outputs.slides_files }}"

          for folder in $slides_folders; do
            cp -rT template slides/$folder
            pnpm run slidev:build slides/$folder/slide.md --out ${{ github.workspace }}/dist/$folder --base /$folder/
            echo $folder
          done
      
      - name: Check dist
        if: ${{ steps.changes.outputs.slides_files }}
        run: ls -la dist

      - name: Update slides.json
        run: tree -J -L 1 slides -o ${{ github.workspace }}/dist/slides.json

      - name: Identify unchanged folder
        id: not_changed
        run: |
          files="${{ steps.changes.outputs.slides_files }}"
          if [ -n "$files" ]; then
              echo "Result is not empty:"
          else
              files=$(ls -d slides/*)
          fi
          N_FILES=$(echo "$files" | awk '{OFS="\n"; $1=$1}1' | grep -v -f - <(ls -d slides/* | awk -F'/' '{print $NF}'))
          if [ -n "$N_FILES" ]; then
              echo "N_FILES<<EOF" >> $GITHUB_ENV
              for files in $N_FILES; do
                echo "$files" >> $GITHUB_ENV
                echo $files
              done
              echo "" >> $GITHUB_ENV
              echo "EOF" >> $GITHUB_ENV
          else
              echo "N_FILES<<EOF" >> $GITHUB_ENV
              echo "" >> $GITHUB_ENV
              echo "EOF" >> $GITHUB_ENV
          fi
          echo $N_FILES

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          folder: dist
          clean-exclude: |
            ${{ env.N_FILES }}
            /assets
            /index.html
            /vite.svg
            